DROP EXTENSION IF EXISTS vector CASCADE;

DROP TABLE IF EXISTS relationships CASCADE;
DROP TABLE IF EXISTS participants CASCADE;
DROP TABLE IF EXISTS logs CASCADE;
DROP TABLE IF EXISTS goals CASCADE;
DROP TABLE IF EXISTS memories_1536 CASCADE;
DROP TABLE IF EXISTS memories_1024 CASCADE;
DROP TABLE IF EXISTS memories_768 CASCADE;
DROP TABLE IF EXISTS memories_384 CASCADE;
DROP VIEW IF EXISTS memories CASCADE;
DROP TABLE IF EXISTS rooms CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;