#!/bin/bash

echo "🚀 Adding Telegram workflow to n8n..."
echo ""
echo "Since you're already logged in, here's the fastest way:"
echo ""
echo "1. Click the 'Workflows' menu on the left"
echo "2. Click 'Add workflow' → 'Import from File...'"
echo "3. Select this file:"
echo "   /Users/davidlockie/Documents/Projects/Eliza/n8n-workflows/import-workflow.json"
echo ""
echo "OR manually:"
echo ""
echo "1. Click 'New Workflow'"
echo "2. Press Cmd+A to select all (the default trigger)"
echo "3. Press Delete to clear canvas"
echo "4. Press Cmd+V and paste the workflow from paste-this-workflow.json"
echo ""
echo "Then add your Telegram credentials:"
echo "Bot Token: 7565951809:AAEsVFpZDMK0s9FookBRiC3XsDNV7IvZW-s"
echo ""
echo "💰 This saves you $0.25 per broadcast ($1,700-3,500/year)!"